const SET_CURR_BOOK = 'SET_CURR_BOOK'
const SET_CURR_CHAPTER_LIST = 'SET_CURR_CHAPTER_LIST'
const SET_CURR_CHAPTER = 'SET_CURR_CHAPTER'
const SET_CURR_CONTENT = 'SET_CURR_CONTENT'
const REVERSE_CHAPTER = 'REVERSE_CHAPTER'
const CHANGE_SKIN = 'CHANGE_SKIN'
const CHANGE_MODE = 'CHANGE_MODE'
const ZOOM_IN = 'ZOOM_IN'
const ZOOM_OUT = 'ZOOM_OUT'

export { SET_CURR_BOOK, SET_CURR_CHAPTER_LIST,
         SET_CURR_CHAPTER, SET_CURR_CONTENT,
         REVERSE_CHAPTER, CHANGE_SKIN, CHANGE_MODE,
         ZOOM_IN, ZOOM_OUT }
