const SET_CURR_BOOK = 'SET_CURR_BOOK'
const ADD_BOOK = 'ADD_BOOK'
const REMOVE_BOOK = 'REMOVE_BOOK'
const SET_CURR_CHAPTER_LIST = 'SET_CURR_CHAPTER_LIST'
const SET_CURR_CHAPTER = 'SET_CURR_CHAPTER'
const SET_CURR_CONTENT = 'SET_CURR_CONTENT'
const REVERSE_CHAPTER = 'REVERSE_CHAPTER'
const CHANGE_SKIN = 'CHANGE_SKIN'
const TOGGLE_NIGHT_MODE = 'TOGGLE_NIGHT_MODE'
const ZOOM_IN = 'ZOOM_IN'
const ZOOM_OUT = 'ZOOM_OUT'
const UPDATE_TOP = 'UPDATE_TOP'

export { SET_CURR_BOOK, SET_CURR_CHAPTER_LIST,
         ADD_BOOK, REMOVE_BOOK,
         SET_CURR_CHAPTER, SET_CURR_CONTENT,
         REVERSE_CHAPTER, CHANGE_SKIN, TOGGLE_NIGHT_MODE,
         ZOOM_IN, ZOOM_OUT,
         UPDATE_TOP }
