const SET_CURR_BOOK = 'SET_CURR_BOOK'
const SET_CURR_CHAPTER_LIST = 'SET_CURR_CHAPTER_LIST'
const SET_CURR_CHAPTER = 'SET_CURR_CHAPTER'
const SET_CURR_CONTENT = 'SET_CURR_CONTENT'
const REVERSE_CHAPTER = 'REVERSE_CHAPTER'

export { SET_CURR_BOOK, SET_CURR_CHAPTER_LIST, SET_CURR_CHAPTER, SET_CURR_CONTENT, REVERSE_CHAPTER }